version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Django's default port
    environment:
      - DJANGO_SETTINGS_MODULE=employee_management.settings
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: Sonu@123
      POSTGRES_DB: employee_management
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
